#!/bin/sh
set -eu
go test ./...
go vet ./...
go test -race ./...
CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -trimpath -ldflags="-s -w" -o /tmp/mailpush-armv7 ./cmd/mailpush
file /tmp/mailpush-armv7 | grep -q 'ARM'
echo "All checks passed."
